### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by lopezm94** [learn-co-curriculum/sinatra-dynamic-routes-codealong#18]
In `spec/sinatradynamic_routes_codealong_spec.rb` the first line should be `require 'spec_helper'` instead of `require 'pry'`

**Comment by pickledyamsman** [comment]
@aturkewi This is still an issue on March 14th. and switching to spec_helper fixes the problem.

**Comment by jmburges** [comment]
Closed with commit 91fbd10ab20e41a79ad058e8d4b972ce7212ed80
